dist: trusty

language: python

python:
    - '3.6'

addons:
  apt:
    packages:
      # can't use mpl from system, need mpl 2.0 for MPLBACKEND to work
      # correctly
      # - python-numpy
      - python3-numpy
      # - python-scipy
      - python3-scipy

before_install:
  - pip install -U pytest pytest-cov codecov
  # pylint

install:
  - pip install .

script:
#  - pylint myFuns/
#  - pylint tests/*.py
#  - cd tests && MPLBACKEND=Agg pytest --cov myFuns
  - pytest --cov=./

after_success:
  # - bash <(curl -s https://codecov.io/bash)
  - codecov